### ISSUE TITLE
Improve default meshing strategy of solar analysis geometries

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#626] opened 2021-06-28 14:02 UTC
![image](https://user-images.githubusercontent.com/55989746/123648718-7732aa80-d829-11eb-942e-228bd9be3fdb.png)
![image](https://user-images.githubusercontent.com/55989746/123648726-79950480-d829-11eb-825e-748e938058ac.png)

Hi,

if I'm not mistaken, there was no mentioning of this mesh setting in either the instruction or the YouTube tutorial. However, I do find the granularity of the geometry meshing important. For my own exercise (see attached images), when I use U=V=2, the mesh does not reflect the geometry I designed at all. So maybe in the instruction, an additional reminder to check the mesh is necessary, because by default the mesh preview is turned off.

Keyword: FEATURE

**Comment by ChrisZenhub** [comment] 2022-01-03 09:14
To Do:
- add default option in `GhSolar` to make uniform meshing according to grid spacing, similar to how Radiance/Daysim (and thus ClimateStudio and Honeybee) do it. So user specifies, e.g., grid spacing 0.5 m, and on a regular grid, sensor points will be added and an analysis mesh created accordingly. Additional vertices added at the mesh edges to keep the original outline of the geometry.
- keep the current meshing strategy as optional (explicit mesh input)

**Comment by ChrisZenhub** [comment] 2022-08-01 01:38
closing as duplicate of #714

**Closed by ChrisZenhub** 2022-08-01 01:38 UTC
Labels: feature 💡
