### ISSUE TITLE
Building Lifetime

### ISSUE THREAD

**Issue by pedrammrbn** [architecture-building-systems/hive#804] opened 2023-01-25 14:34 UTC
How is the building's lifetime defined? The value appears to currently be 80 but is not part of the information passed on in the SIA 2024 room object.  It would be beneficial to be able to see and override the value as part of the building inputs form.

![image](https://user-images.githubusercontent.com/108935429/214590764-76019035-2103-44b7-8601-1e7be6783ac7.png)

**Comment by christophwaibel** [comment] 2023-03-01 18:06
closing as duplicate of #743

**Closed by christophwaibel** 2023-03-01 18:06 UTC
Labels: enhancement 🥊
