### ISSUE TITLE
Energy Systems Lifetime

### ISSUE THREAD

**Issue by pedrammrbn** [architecture-building-systems/hive#802] opened 2023-01-19 14:50 UTC
Adding lifetime input for energy systems form.

![image](https://user-images.githubusercontent.com/108935429/213473481-dc906f55-fe6a-4204-910d-d643a4e4d67e.png)

**Comment by christophwaibel** [comment] 2023-03-01 18:06
closing as duplicate of #811

**Closed by christophwaibel** 2023-03-01 18:06 UTC
Labels: feature 💡
