### ISSUE TITLE
Bar plot or curve plot: heating / cooling / dhw hourly annual (8760)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#210] opened 2020-04-16 12:51 UTC
The current GHVisualization component has a rough implementation that has a main drawback:

- it is very slow

I suggest re-creating this as a (possibly down-scaled to the number of pixels available in the GHCapsule?) curve plot.

**Comment by amraladdin** [comment] 2020-04-21 11:54
Hey @daren-thomas what is the number of pixels available in a GHCapsule?

**Comment by daren-thomas** [comment] 2020-04-22 15:02
hey @amraladdin great question! as far as I can tell it depends on your screen resolution and the width and height of the capsule. It's not a fixed amount. Any plot designs need to take this into account. We can specify a minimum width and height though. As well as a default one, I think.

**Comment by ChrisZenhub** [comment] 2021-05-27 08:16
closing as duplicate of #575

**Closed by ChrisZenhub** 2021-05-27 08:16 UTC
Labels: enhancement/feature
