### ISSUE TITLE
Set up continuous integration to run all the tests on merge to master / create pull request

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#94] opened 2019-07-26 09:36 UTC
Similar to how the Jenkins works for the CEA (maybe even re-use the Jenkins server):

- on each merge to master / push to pull-request: run `honey-badger -t path/to/hive.git`

**Comment by maxenceryan** [comment] 2021-06-25 15:46
Duplicate of #592

**Closed by maxenceryan** 2021-06-25 15:46 UTC
Labels: feature 💡
