### ISSUE TITLE
calculate tau based on construction and geometry

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#469] opened 2020-10-19 14:38 UTC
![image](https://user-images.githubusercontent.com/21927657/96465668-8177c000-1229-11eb-8c8a-f43ae5b471a0.png)

Currently, we use tau from SIA2024 database

**Comment by ChrisZenhub** [comment] 2020-11-26 13:13
closed as duplicate of #516

**Closed by ChrisZenhub** 2020-11-26 13:13 UTC
Labels: enhancement/feature
