### ISSUE TITLE
PV Surfaces Not Being Saved on Certain File Opening Scenarios

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/hive#669] opened 2021-11-10 12:36 UTC
**Describe the bug**
I was looking at a student file that they had informed me was not showing their PV results, although they had assigned the surface. Depending on how I open the file the PV is assigned to the mesh (double-clicking on it in Explorer)or it isn't (open through Grasshopper)

**To Reproduce**
1. Use the attached file. Double click to open. There will be no assigned PV to the solar surface.
2. Open a new rhino window and then grasshopper. Open the file. There will be assigned PV to the solar surface.

**Expected behavior**
If PV was assigned to a surface in the past then it should always be assigned. 

**Software**
 - Rhino 7 SR11 on Windows 10
 - Hive 1.10.2 (https://github.com/architecture-building-systems/hive/releases/tag/v1.10.2) 
 - 

**Additional context**
Huge caveat here is that I have not tested this on other Hive Versions.
File is here --> https://drive.google.com/file/d/1HKfomC3wovDvweTG9A6L97siI68zxHyj/view?usp=sharing

**Comment by ChrisZenhub** [comment] 2021-11-15 10:14
with internalized data, we could not reproduce this bug (rhino 6, hive 1.3.x current master branch). 
Mabye this bug is no bug, because in your example it needed a .3dm? @justinfmccarty

**Comment by ChrisZenhub** [comment] 2021-11-15 10:31
just tried with referenced data from a .3dm: opening the .gh with a double click results in red components (because it is missing the .3dm), but when opening that .3dm subsequently, it properly recognized the data (and the PV)

**Comment by ChrisZenhub** [comment] 2021-11-22 10:39
@justinfmccarty could you let us know if this now works for you? then we can close this issue

**Comment by justinfmccarty** [comment] 2021-11-22 10:50
@ChrisZenhub You can close this. The original .gh file I linked to had everything internalised, so no need for a .3dm to reference to. However I am not able to recreate the issue anymore across versions so it looks like it was solved inadvertently.

**Closed** 2021-11-22 10:52 UTC
Labels: bug 👾
