### ISSUE TITLE
C# simple solar very slow with many surfaces

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#713] opened 2022-01-11 08:44 UTC
**Describe the bug**
The migrated C# component `GhSolarUnobstructed.cs` is extremely slow with many inputs. The problem is likely rooted in `RegisterInputParams`: it reads tilt angles and azimuths in as lists, however surface area only as item. Therefore, it probably conducts `p.CalcIrradiationMT` way too many times. 

**Expected behavior**
Should be faster. Change inputs either all to items, or all (include surface area) to lists and make proper multi-threading.

**Software**
 - Rhino Version 7
 - Hive Version 1.14

**Comment by ChrisZenhub** [comment] 2022-04-07 12:26
@philipschulz strangely, I cannot reproduce it with the current master
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/78763137-0b4d-4bf4-8343-27a9e5452951)

top is python, bottom is c#, testing with 100 PV surfaces.

If you also can't reproduce it, you can close this issue

**Closed** 2022-04-08 10:54 UTC
Labels: bug 👾
