### ISSUE TITLE
Supply / Storage visualization

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#214] opened 2020-04-16 12:55 UTC
Bar plot for capacities of supply / storage technologies. ("capacity_" in the ghpython example script, and "area_". Note, that the plot needs different axes description for the Y-axis: storage in kWh, supply/conversion tech in kW, and solar tech in m^2)

NOTE: I'm not sure Hive.IO.Results contains this information?

**Comment by amraladdin** [comment] 2020-05-08 10:14
@daren-thomas I'm not sure I quite get this issue. Perhaps we can talk about it next week?

**Comment by daren-thomas** [comment] 2020-05-11 08:49
@amraladdin I'm not sure myself - would you mind asking @christophwaibel? I think I copy/pasted a comment of his from another issue to break it out into this issue.

**Comment by christophwaibel** [comment] 2020-05-11 08:59
A plot (barplot is just a suggestion) that shows *capacities* of energy technologies.
Our other plots so far only showed operation.

![image](https://user-images.githubusercontent.com/21927657/81543423-55047180-9376-11ea-8e76-9a7e976561df.png)

**Comment by amraladdin** [comment] 2020-05-11 09:02
Looks great! Thank you for the quick reply :) I see now what you meant.

**Comment by ChrisZenhub** [comment] 2020-06-18 09:35
closed as duplicate of #215

**Closed by ChrisZenhub** 2020-06-18 09:35 UTC
