### ISSUE TITLE
Demand simulation only works with windows

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#715] opened 2022-01-11 09:10 UTC
**Describe the bug**
This bug keeps coming back with every Hive version ;-(
Demand simulation only works with windows. It should also work for a box without windows.

**Screenshots**
<img width="558" alt="image" src="https://user-images.githubusercontent.com/21927657/148913645-e1721d22-90a4-4c90-a1ef-59fdf1c054b6.png">

**Software**
 - Hive Version 1.14

**how to reproduce**
Get the current master, install it. Open the main template file (`...\hive\GrasshopperExamples\LectureExercises\EaCS3_E04_Hive_Template.gh`), and remove the windows from the Hive-Building-input. The simulation will not be able to run and no results will be produced.

**Expected Behavior**
Demand simulations should also work without windows on a building.

**Comment by ChrisZenhub** [comment] 2022-02-10 09:16
to be checked, but I think the respective GH_input_params in the GH_Component just needs to be set to "optional".

**Comment by ChrisZenhub** [comment] 2022-02-14 10:30
ok strange... I can't reproduce this bug anymore 
@mmatache25 please also try with your Mac and if you also don't get this bug, close this issue

**Comment by mmatache25** [comment] 2022-02-21 09:05
@christophwaibel the demand simulation works with or without windows, it works as expected.

**Closed** 2022-02-21 09:06 UTC
Labels: bug 👾
